services:
  - type: web
    name: vidly-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        scope: shared
      - key: vidly_jwtPrivateKey
        scope: shared
